spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8788/realms/scat6-app
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/mydatabase
      database: mydatabase